In [4]:
import pandas as pd

In [5]:
data = pd.read_csv(r'D:\SQL\Supply_Chain_Mgmt\Data\DataCoSupplyChainDataset.csv',
encoding='latin-1',
sep=';'
)
data.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [6]:
df = pd.DataFrame(data)
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [10]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [11]:
df.columns.to_list()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [13]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [14]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [15]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [16]:
columns_to_drop = [
    "Customer Email",
    "Customer Fname",
    "Customer Lname",
    "Customer Password",
    "Customer Street",
    "Customer Zipcode",
    "Latitude",
    "Longitude",
    "Product Image",
    "Product Description",
    "Order Zipcode"
]

In [17]:
df = df.drop(columns=columns_to_drop)

In [18]:
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Southeast Asia,Java Occidental,COMPLETE,1360,73,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,South Asia,Rajastán,PENDING,1360,73,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,South Asia,Rajastán,CLOSED,1360,73,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Oceania,Queensland,COMPLETE,1360,73,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Oceania,Queensland,PENDING_PAYMENT,1360,73,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,Eastern Asia,Shanghái,CLOSED,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,Eastern Asia,Osaka,COMPLETE,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,Oceania,Australia del Sur,PENDING,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,Oceania,Australia del Sur,PENDING_PAYMENT,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,South Asia,Tamil Nadu,PENDING_PAYMENT,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [20]:
df_original = df.copy()
df = df_original.copy()

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 42 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Id                    180519 non-null  int64
 12  Customer Segment               180519 non-null  object
 13  Customer State                 180519 non-null  object
 14  Department Id                  180519 non-null  int64
 15  Department Name                180519 non-null  object
 16  Market                         180519 non-null  object
 17  Order City                     180519 non-null  object
 18  Order Country                  180519 non-null  object
 19  Order Customer Id              180519 non-null  int64
 20  order date (DateOrders)        180519 non-null  object
 21  Order Id                       180519 non-null  int64
 22  Order Item Cardprod Id         180519 non-null  int64
 23  Order Item Discount            180519 non-null  float64
 24  Order Item Discount Rate       180519 non-null  float64
 25  Order Item Id                  180519 non-null  int64
 26  Order Item Product Price       180519 non-null  float64
 27  Order Item Profit Ratio        180519 non-null  float64
 28  Order Item Quantity            180519 non-null  int64
 29  Sales                          180519 non-null  float64
 30  Order Item Total               180519 non-null  float64
 31  Order Profit Per Order         180519 non-null  float64
 32  Order Region                   180519 non-null  object
 33  Order State                    180519 non-null  object
 34  Order Status                   180519 non-null  object
 35  Product Card Id                180519 non-null  int64
 36  Product Category Id            180519 non-null  int64
 37  Product Name                   180519 non-null  object
 38  Product Price                  180519 non-null  float64
 39  Product Status                 180519 non-null  int64
 40  shipping date (DateOrders)     180519 non-null  object
 41  Shipping Mode                  180519 non-null  object
dtypes: float64(10), int64(14), object(18)
memory usage: 57.8+ MB

In [22]:
df.columns.value_counts()

Type                             1
Days for shipping (real)         1
Days for shipment (scheduled)    1
Benefit per order                1
Sales per customer               1
Delivery Status                  1
Late_delivery_risk               1
Category Id                      1
Category Name                    1
Customer City                    1
Customer Country                 1
Customer Id                      1
Customer Segment                 1
Customer State                   1
Department Id                    1
Department Name                  1
Market                           1
Order City                       1
Order Country                    1
Order Customer Id                1
order date (DateOrders)          1
Order Id                         1
Order Item Cardprod Id           1
Order Item Discount              1
Order Item Discount Rate         1
Order Item Id                    1
Order Item Product Price         1
Order Item Profit Ratio          1
Order Item Quantity              1
Sales                            1
Order Item Total                 1
Order Profit Per Order           1
Order Region                     1
Order State                      1
Order Status                     1
Product Card Id                  1
Product Category Id              1
Product Name                     1
Product Price                    1
Product Status                   1
shipping date (DateOrders)       1
Shipping Mode                    1
Name: count, dtype: int64

In [23]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Id', 'Customer Segment', 'Customer State',
       'Department Id', 'Department Name', 'Market', 'Order City',
       'Order Country', 'Order Customer Id', 'order date (DateOrders)',
       'Order Id', 'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Product Card Id', 'Product Category Id',
       'Product Name', 'Product Price', 'Product Status',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [ ]:
# Creating a new customer_table from existing table.
customer_cols = [
    "Customer Id",
    "Customer Fname",
    "Customer Lname",
    "Customer City",
    "Customer State",
    "Customer Country",
    "Customer Segment",
    "Customer Zipcode"
]

In [9]:
customer_table = df[customer_cols].drop_duplicates()
print(customer_table.shape)
customer_table.head()

(20652, 8)

,Customer Id,Customer Fname,Customer Lname,Customer City,Customer State,Customer Country,Customer Segment,Customer Zipcode
0,20755,Cally,Holloway,Caguas,PR,Puerto Rico,Consumer,725.0
1,19492,Irene,Luna,Caguas,PR,Puerto Rico,Consumer,725.0
2,19491,Gillian,Maldonado,San Jose,CA,EE. UU.,Consumer,95125.0
3,19490,Tana,Tate,Los Angeles,CA,EE. UU.,Home Office,90027.0
4,19489,Orli,Hendricks,Caguas,PR,Puerto Rico,Corporate,725.0

In [ ]:
# Creating a new product_table from existing table.
product_cols = [
    "Product Card Id",
    "Product Name",
    "Category Id",
    "Category Name",
    "Department Id",
    "Department Name",
    "Product Price"
]
product_table = df[product_cols].drop_duplicates()
print(product_table.shape)
product_table.head()

(118, 7)

,Product Card Id,Product Name,Category Id,Category Name,Department Id,Department Name,Product Price
0,1360,Smart watch,73,Sporting Goods,2,Fitness,327.750000
48,365,Perfect Fitness Perfect Rip Deck,17,Cleats,4,Apparel,59.990002
49,627,Under Armour Girls' Toddler Spine Surge Runni,29,Shop By Sport,5,Golf,39.990002
50,502,Nike Men's Dri-FIT Victory Golf Polo,24,Women's Apparel,5,Golf,50.000000
55,278,Under Armour Men's Compression EV SL Slide,13,Electronics,3,Footwear,44.990002

In [14]:
# Creating a new order_table from existing table.
order_cols = [
    "Order Id",
    "order date (DateOrders)",
    "Order Status",
    "Order City",
    "Order State",
    "Order Country",
    "Order Region",
    "Market"
]
order_table = df[order_cols].drop_duplicates()
print(order_table.shape)
order_table.head()

(65752, 8)

,Order Id,order date (DateOrders),Order Status,Order City,Order State,Order Country,Order Region,Market
0,77202,1/31/2018 22:56,COMPLETE,Bekasi,Java Occidental,Indonesia,Southeast Asia,Pacific Asia
1,75939,1/13/2018 12:27,PENDING,Bikaner,Rajastán,India,South Asia,Pacific Asia
2,75938,1/13/2018 12:06,CLOSED,Bikaner,Rajastán,India,South Asia,Pacific Asia
3,75937,1/13/2018 11:45,COMPLETE,Townsville,Queensland,Australia,Oceania,Pacific Asia
4,75936,1/13/2018 11:24,PENDING_PAYMENT,Townsville,Queensland,Australia,Oceania,Pacific Asia

In [15]:
# Creating a new shipping_table from existing table.
shipping_cols = [
    "Order Id",
    "Shipping Mode",
    "Delivery Status",
    "Late_delivery_risk",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "shipping date (DateOrders)"
]
shipping_table = df[shipping_cols].drop_duplicates()
print(shipping_table.shape)
shipping_table.head()

(65752, 7)

,Order Id,Shipping Mode,Delivery Status,Late_delivery_risk,Days for shipping (real),Days for shipment (scheduled),shipping date (DateOrders)
0,77202,Standard Class,Advance shipping,0,3,4,2/3/2018 22:56
1,75939,Standard Class,Late delivery,1,5,4,1/18/2018 12:27
2,75938,Standard Class,Shipping on time,0,4,4,1/17/2018 12:06
3,75937,Standard Class,Advance shipping,0,3,4,1/16/2018 11:45
4,75936,Standard Class,Advance shipping,0,2,4,1/15/2018 11:24

In [16]:
# Creating a new sales_table from existing table.
sales_cols = [
    "Order Id",
    "Customer Id",
    "Product Card Id",
    "Sales",
    "Order Item Quantity",
    "Benefit per order",
    "Order Profit Per Order"
]
sales_table = df[sales_cols].drop_duplicates()
print(sales_table.shape)
sales_table.head()

(180511, 7)

,Order Id,Customer Id,Product Card Id,Sales,Order Item Quantity,Benefit per order,Order Profit Per Order
0,77202,20755,1360,327.75,1,91.250000,91.250000
1,75939,19492,1360,327.75,1,-249.089996,-249.089996
2,75938,19491,1360,327.75,1,-247.779999,-247.779999
3,75937,19490,1360,327.75,1,22.860001,22.860001
4,75936,19489,1360,327.75,1,134.210007,134.210007

In [17]:
customer_table.to_csv("customers.csv", index=False)

product_table.to_csv("products.csv", index=False)

order_table.to_csv("orders.csv", index=False)

shipping_table.to_csv("shipping.csv", index=False)

sales_table.to_csv("sales_fact.csv", index=False)

In [18]:
customers = pd.read_csv("customers.csv", sep=";")
products = pd.read_csv("products.csv", sep=";")
orders = pd.read_csv("orders.csv", sep=";")
shipping = pd.read_csv("shipping.csv", sep=";")
sales_fact = pd.read_csv("sales_fact.csv", sep=";")

In [19]:
customers.shape
products.shape
orders.shape
shipping.shape
sales_fact.shape

(180511, 7)

In [20]:
sales_table.groupby("Customer Id")["Sales"].sum()

Customer Id
1         499.950012
2        1819.730034
3        3537.680094
4        1719.630030
5        1274.750023
            ...
20753     215.820007
20754     215.820007
20755     327.750000
20756      11.540000
20757      39.750000
Name: Sales, Length: 20652, dtype: float64

In [21]:
product_table.groupby("Category Name")["Product Price"].mean()

Category Name
Accessories               24.990000
As Seen on  TV!           99.989998
Baby                      59.080002
Baseball & Softball       84.990003
Basketball               533.323324
Books                     31.080000
Boxing & MMA              79.983332
CDs                       11.290000
Cameras                  452.040008
Camping & Hiking         299.980011
Cardio Equipment          64.994999
Children's Clothing      357.100006
Cleats                   179.989996
Computers               1500.000000
Consumer Electronics     252.880005
Crafts                   461.480011
DVDs                     164.380005
Electronics               39.353637
Fishing                  399.980011
Fitness Accessories      317.489996
Garden                   532.580017
Girls' Apparel            41.247500
Golf Apparel              89.990001
Golf Bags & Carts        169.990005
Golf Balls                17.590000
Golf Gloves              126.418571
Golf Shoes                88.250000
Health and Beauty        293.040008
Hockey                   125.663330
Hunting & Shooting        92.993335
Indoor/Outdoor Games      49.980000
Kids' Golf Clubs         249.856246
Lacrosse                  62.489999
Men's Clothing           210.850006
Men's Footwear           129.990005
Men's Golf Clubs         118.740002
Music                    260.649994
Pet Supplies              84.400002
Shop By Sport             89.993336
Soccer                   102.489998
Sporting Goods           327.750000
Strength Training        862.993327
Tennis & Racquet          44.990002
Toys                      11.540000
Trade-In                  75.990001
Video Games               39.750000
Water Sports             274.989998
Women's Apparel           50.000000
Women's Clothing         215.820007
Women's Golf Clubs       129.990000
Name: Product Price, dtype: float64

In [22]:
sales_table.merge(product_table,on="Product Card Id")

,Order Id,Customer Id,Product Card Id,Sales,Order Item Quantity,Benefit per order,Order Profit Per Order,Product Name,Category Id,Category Name,Department Id,Department Name,Product Price
0,77202,20755,1360,327.750000,1,91.250000,91.250000,Smart watch,73,Sporting Goods,2,Fitness,327.750000
1,75939,19492,1360,327.750000,1,-249.089996,-249.089996,Smart watch,73,Sporting Goods,2,Fitness,327.750000
2,75938,19491,1360,327.750000,1,-247.779999,-247.779999,Smart watch,73,Sporting Goods,2,Fitness,327.750000
3,75937,19490,1360,327.750000,1,22.860001,22.860001,Smart watch,73,Sporting Goods,2,Fitness,327.750000
4,75936,19489,1360,327.750000,1,134.210007,134.210007,Smart watch,73,Sporting Goods,2,Fitness,327.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
180506,26043,1005,1004,399.980011,1,40.000000,40.000000,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180507,26037,9141,1004,399.980011,1,-613.770019,-613.770019,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180508,26024,291,1004,399.980011,1,141.110001,141.110001,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180509,26022,2813,1004,399.980011,1,186.229996,186.229996,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180510,26018,7547,1004,399.980011,1,168.949997,168.949997,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011