In [1]:
import pandas as pd

In [2]:
cust_df = pd.read_csv("customers.csv",sep=";")
prod_df = pd.read_csv("products.csv",sep=";")
ord_df = pd.read_csv("orders.csv",sep=";")
ship_df = pd.read_csv("shipping.csv",sep=";")
sales_df = pd.read_csv("sales_fact.csv",sep=";")

In [5]:
cust_df

,Customer Id,Customer Fname,Customer Lname,Customer City,Customer State,Customer Country,Customer Segment,Customer Zipcode
0,1,Richard,Hernandez,Brownsville,TX,EE. UU.,Consumer,78521.0
1,2,Mary,Barrett,Littleton,CO,EE. UU.,Consumer,80126.0
2,3,Ann,Smith,Caguas,PR,Puerto Rico,Consumer,725.0
3,4,Mary,Jones,San Marcos,CA,EE. UU.,Consumer,92069.0
4,5,Robert,Hudson,Caguas,PR,Puerto Rico,Home Office,725.0
...,...,...,...,...,...,...,...,...
20647,20753,Chava,Velez,Caguas,PR,Puerto Rico,Consumer,725.0
20648,20754,Stacey,Weber,Plainfield,IL,EE. UU.,Consumer,60544.0
20649,20755,Cally,Holloway,Caguas,PR,Puerto Rico,Consumer,725.0
20650,20756,Cherokee,Callahan,Berwyn,IL,EE. UU.,Corporate,60402.0
20651,20757,Katelyn,Gonzales,Miami,FL,EE. UU.,Corporate,33126.0

In [6]:
prod_df

,Product Card Id,Product Name,Category Id,Category Name,Department Id,Department Name,Product Price
0,1360,Smart watch,73,Sporting Goods,2,Fitness,327.750000
1,365,Perfect Fitness Perfect Rip Deck,17,Cleats,4,Apparel,59.990002
2,627,Under Armour Girls' Toddler Spine Surge Runni,29,Shop By Sport,5,Golf,39.990002
3,502,Nike Men's Dri-FIT Victory Golf Polo,24,Women's Apparel,5,Golf,50.000000
4,278,Under Armour Men's Compression EV SL Slide,13,Electronics,3,Footwear,44.990002
...,...,...,...,...,...,...,...
113,646,Merrell Women's Grassbow Sport Hiking Shoe,30,Men's Golf Clubs,6,Outdoors,99.989998
114,1361,Toys,74,Toys,7,Fan Shop,11.540000
115,1073,Pelican Sunstream 100 Kayak,48,Water Sports,7,Fan Shop,199.990005
116,1059,Pelican Maverick 100X Kayak,48,Water Sports,7,Fan Shop,349.989990
117,1014,O'Brien Men's Neoprene Life Vest,46,Indoor/Outdoor Games,7,Fan Shop,49.980000

In [42]:
ord_df

,Order Id,order date (DateOrders),Order Status,Order City,Order State,Order Country,Order Region,Market
0,77202,1/31/2018 22:56,COMPLETE,Bekasi,Java Occidental,Indonesia,Southeast Asia,Pacific Asia
1,75939,1/13/2018 12:27,PENDING,Bikaner,Rajastán,India,South Asia,Pacific Asia
2,75938,1/13/2018 12:06,CLOSED,Bikaner,Rajastán,India,South Asia,Pacific Asia
3,75937,1/13/2018 11:45,COMPLETE,Townsville,Queensland,Australia,Oceania,Pacific Asia
4,75936,1/13/2018 11:24,PENDING_PAYMENT,Townsville,Queensland,Australia,Oceania,Pacific Asia
...,...,...,...,...,...,...,...,...
65747,26773,1/26/2016 19:25,CLOSED,Ho Chi Minh City,Ciudad Ho Chi Minh,Vietnam,Southeast Asia,Pacific Asia
65748,26463,1/22/2016 6:49,PENDING_PAYMENT,Ezhou,Hubei,China,Eastern Asia,Pacific Asia
65749,26383,1/21/2016 2:47,CLOSED,Tawau,Sabah,Malasia,Southeast Asia,Pacific Asia
65750,26327,1/20/2016 7:10,ON_HOLD,Semarang,Java Central,Indonesia,Southeast Asia,Pacific Asia
65751,26118,1/17/2016 5:56,SUSPECTED_FRAUD,Ratlam,Madhya Pradesh,India,South Asia,Pacific Asia

In [8]:
ship_df

,Order Id,Shipping Mode,Delivery Status,Late_delivery_risk,Days for shipping (real),Days for shipment (scheduled),shipping date (DateOrders)
0,77202,Standard Class,Advance shipping,0,3,4,2/3/2018 22:56
1,75939,Standard Class,Late delivery,1,5,4,1/18/2018 12:27
2,75938,Standard Class,Shipping on time,0,4,4,1/17/2018 12:06
3,75937,Standard Class,Advance shipping,0,3,4,1/16/2018 11:45
4,75936,Standard Class,Advance shipping,0,2,4,1/15/2018 11:24
...,...,...,...,...,...,...,...
65747,26773,First Class,Late delivery,1,2,1,1/28/2016 19:25
65748,26463,Standard Class,Shipping on time,0,4,4,1/26/2016 6:49
65749,26383,Second Class,Late delivery,1,4,2,1/25/2016 2:47
65750,26327,Standard Class,Advance shipping,0,3,4,1/23/2016 7:10
65751,26118,Standard Class,Shipping canceled,0,4,4,1/21/2016 5:56

In [9]:
sales_df

,Order Id,Customer Id,Product Card Id,Sales,Order Item Quantity,Benefit per order,Order Profit Per Order
0,77202,20755,1360,327.750000,1,91.250000,91.250000
1,75939,19492,1360,327.750000,1,-249.089996,-249.089996
2,75938,19491,1360,327.750000,1,-247.779999,-247.779999
3,75937,19490,1360,327.750000,1,22.860001,22.860001
4,75936,19489,1360,327.750000,1,134.210007,134.210007
...,...,...,...,...,...,...,...
180506,26043,1005,1004,399.980011,1,40.000000,40.000000
180507,26037,9141,1004,399.980011,1,-613.770019,-613.770019
180508,26024,291,1004,399.980011,1,141.110001,141.110001
180509,26022,2813,1004,399.980011,1,186.229996,186.229996
180510,26018,7547,1004,399.980011,1,168.949997,168.949997

In [10]:
cust_df['Customer Id'].nunique()

20652

In [13]:
cust_df['Customer City'].nunique()
cust_df['Customer City'].unique()

array(['Brownsville', 'Littleton', 'Caguas', 'San Marcos', 'Passaic',
       'Lawrence', 'Stafford', 'San Antonio', 'Pico Rivera', 'Fontana',
       'Taylor', 'Martinez', 'West New York', 'North Bergen', 'San Juan',
       'Peoria', 'Glenview', 'Longview', 'Fort Worth', 'Albuquerque',
       'Norfolk', 'Oceanside', 'Opelousas', 'Long Beach', 'Brooklyn',
       'Duluth', 'Napa', 'Denver', 'Freeport', 'Strongsville',
       'San Bernardino', 'Chicago', 'Roswell', 'Phoenix', 'Baltimore',
       'Sunnyvale', 'Webster', 'Princeton', 'Los Angeles', 'Philadelphia',
       'Vista', 'Jacksonville', 'Parkville', 'Knoxville', 'Ithaca',
       'Tampa', 'Atlanta', 'Escondido', 'Spring', 'Annapolis',
       'Hyattsville', 'Las Vegas', 'Dorchester Center', 'Broomfield',
       'Saint Paul', 'Bronx', 'Beaverton', 'Middletown', 'Bellflower',
       'West Covina', 'La Crosse', 'Ogden', 'Cincinnati', 'Bend',
       'Oxnard', 'Amarillo', 'Augusta', 'Aurora', 'Methuen', 'Lynn',
       'Broken Arrow', 'San Diego', 'Opa Locka', 'Dayton', 'Hanover',
       'Colton', 'Union', 'Richmond', 'Hollywood', 'Brandon',
       'Citrus Heights', 'Corona', 'Hialeah', 'Rio Rancho', 'Antioch',
       'Florissant', 'Columbus', 'Chino', 'Lombard', 'Dundalk', 'Irwin',
       'Hayward', 'Lindenhurst', 'Louisville', 'Portland', 'Gaithersburg',
       'Modesto', 'Dearborn', 'Lancaster', 'Pompano Beach', 'Bayamon',
       'Lawrenceville', 'South Ozone Park', 'Enfield', 'Flushing',
       'Visalia', 'La Puente', 'Salinas', 'Carol Stream', 'Wheeling',
       'Tempe', 'Wyoming', 'Glendale', 'Miami', 'Piscataway', 'San Jose',
       'Mcallen', 'Hamilton', 'Mililani', 'Yonkers', 'Oak Lawn',
       'Houston', 'Richardson', 'Humacao', 'North Hollywood', 'Cerritos',
       'Goleta', 'Dubuque', 'Fremont', 'Jamaica', 'Juana Diaz',
       'Wilmington', 'Santa Cruz', 'Morristown', 'Bristol', 'Newark',
       'Detroit', 'Troy', 'Plano', 'Fullerton', 'New Haven', 'York',
       'Austin', 'Milwaukee', 'Wayne', 'Ann Arbor', 'New York',
       'Washington', 'Carrollton', 'Placentia', 'Tracy', 'Denton',
       'Carlsbad', 'Dallas', 'Stockton', 'Carmichael', 'Catonsville',
       'Diamond Bar', 'Tulare', 'Garden Grove', 'San Francisco',
       'Union City', 'Mesa', 'Wyandotte', 'Fairfield', 'Huntington Beach',
       'Saginaw', 'Doylestown', 'Lakewood', 'Revere', 'Cumberland',
       'Fort Lauderdale', 'Asheboro', 'Greensboro', 'Potomac', 'Gardena',
       'Round Rock', 'San Ramon', 'Carlisle', 'Endicott', 'Spring Valley',
       'Porterville', 'Allentown', 'Fort Washington', 'Mission Viejo',
       'Colorado Springs', 'Sanford', 'Milford', 'Morrisville',
       'Far Rockaway', 'Elmhurst', 'Eugene', 'Plainfield',
       'Granada Hills', 'Henderson', 'Greeley', 'Michigan City',
       'South Richmond Hill', 'Orange Park', 'Scottsdale', 'Simi Valley',
       'Rancho Cordova', 'La Habra', 'Stockbridge', 'New Bedford',
       'Taunton', 'Sugar Land', 'Baldwin Park', 'Costa Mesa', 'Ventura',
       'Lynwood', 'Greenville', 'El Cajon', 'Clearfield', 'Compton',
       'Waipahu', 'Meridian', 'Buffalo', 'Joliet', 'Rancho Cucamonga',
       'Kaneohe', 'New Orleans', 'Garland', 'Lynnwood', 'Paramount',
       'Fresno', 'El Paso', 'Smyrna', 'Jackson Heights', 'Anaheim',
       'Honolulu', 'Van Nuys', 'Grand Prairie', 'Riverside', 'Bridgeton',
       'New Castle', 'Cupertino', 'Arecibo', 'Santa Fe', 'Alpharetta',
       'Pomona', 'Pacoima', 'Holland', 'Tucson', 'Chula Vista',
       'Waukegan', 'Harlingen', 'Highland Park', 'Salt Lake City',
       'Hollister', 'Brighton', 'Seattle', 'Vega Baja', 'Moreno Valley',
       'Lilburn', 'Saint Peters', 'Santa Maria', 'Santa Ana', 'Del Rio',
       'Peabody', 'Lawton', 'Indio', 'Pawtucket', 'College Station',
       'Canton', 'Orlando', 'Tallahassee', 'Ypsilanti', 'Elk Grove',
       'San Benito', 'Carolina', 'Rowland Heights', 'Hagerstown',
       'West Orange', 'Crystal Lake', 'Santee', 'Tinley Park', 'Sylmar',
       'El Centro', 'Fountain Valley', 'Greensburg', 'Quincy',
       'Irvington', 'Ontario', 'Bay Shore', 'Marietta', 'Memphis',
       'Santa Clara', 'Chesapeake', 'Reseda', 'Mesquite', 'Walnut',
       'North Las Vegas', 'Kent', 'Hilliard', 'Palatine', 'New Braunfels',
       'Wilkes Barre', 'Winnetka', 'Madison', 'La Mesa', 'Hesperia',
       'Toms River', 'Jonesboro', 'Cleveland', 'Bakersfield',
       'Douglasville', 'New Albany', 'Pittsfield', 'Merced', 'Milpitas',
       'Laredo', 'Sacramento', 'Eagle Pass', 'Silver Spring', 'Metairie',
       'Newburgh', 'Cypress', 'Highland', 'Huntington Station',
       'Hamtramck', 'Weslaco', 'Norcross', 'San Pedro', 'Frankfort',
       'Raleigh', 'Bloomfield', 'Columbia', 'Mentor', 'Marrero', 'Warren',
       'North Richland Hills', 'Danbury', 'Granite City', 'Saint Louis',
       'Ballwin', 'Mount Pleasant', 'Howell', 'Woodbridge',
       'Stone Mountain', 'Elyria', 'Edinburg', 'Annandale', 'Berwyn',
       'Muskegon', 'Chapel Hill', 'O Fallon', 'Fond Du Lac', 'Everett',
       'Bolingbrook', 'Virginia Beach', 'Beloit', 'Hawthorne',
       'Chino Hills', 'Massillon', 'Mission', 'Indianapolis',
       'West Chester', 'Lake Forest', 'Perth Amboy', 'Panorama City',
       'Winter Park', 'Conway', 'Encinitas', 'Guaynabo', 'Canyon Country',
       'Rio Grande', 'Campbell', 'Longmont', 'Bountiful', 'Loveland',
       'Lewisville', 'Palo Alto', 'Lenoir', 'Rosemead', 'Ewa Beach',
       'Rome', 'Montebello', 'Wichita', 'North Hills', 'Massapequa',
       'Stamford', 'La Mirada', 'Alameda', 'Reno', 'Fayetteville',
       'Oregon City', 'Oakland', 'Staten Island', 'Yuma', 'Katy',
       'Rego Park', 'Chandler', 'El Monte', 'Kailua', 'Alhambra',
       'Bell Gardens', 'New Brunswick', 'Sun Valley', 'Jackson',
       'Charlotte', 'Woodside', 'Mayaguez', 'Birmingham', 'Arlington',
       'Westland', 'Salem', 'Lansdale', 'Pharr', 'Burnsville', 'Pekin',
       'Astoria', 'Marion', 'Baytown', 'Yauco', 'Jersey City',
       'Englewood', 'West Haven', 'Elgin', 'Folsom', 'San Sebastian',
       'Summerville', 'Salina', 'Mount Prospect', 'Painesville',
       'Blacksburg', 'Lutz', 'Carson', 'Daly City', 'Moline', 'Irving',
       'Guayama', 'Wheaton', 'Hanford', 'West Jordan', 'Poway',
       'Lockport', 'Brentwood', 'Medina', 'Chicago Heights', 'Woonsocket',
       'Tustin', 'Reynoldsburg', 'Harvey', 'Victorville', 'East Lansing',
       'Kenner', 'Decatur', 'Livermore', 'Norwalk', 'Grove City',
       'Westminster', 'Watsonville', 'Saint Charles', 'Des Plaines',
       'Redmond', 'Aguadilla', 'Laguna Niguel', 'Goose Creek',
       'South El Monte', 'Bowling Green', 'Clarksville', 'Temecula',
       'Valrico', 'Malden', 'Findlay', 'Springfield', 'Westerville',
       'San Pablo', 'Sheboygan', 'Apex', 'Las Cruces', 'Clementon',
       'Apopka', 'Mchenry', 'Bensalem', 'Davis', 'Hampton', 'Sandusky',
       'Glen Burnie', 'Roseburg', 'Gilroy', 'Palmdale', 'Algonquin',
       'Henrico', 'Vacaville', 'Plymouth', 'Pittsburg', 'Tonawanda',
       'Crown Point', 'Madera', 'Levittown', 'Albany', 'Martinsburg',
       'Manchester', 'Cicero', 'Chillicothe', 'North Tonawanda', 'Edison',
       'Hacienda Heights', 'Huntington Park', 'Toa Baja', 'Billings',
       'Forest Hills', 'Mechanicsburg', 'Olathe', 'National City',
       'Rialto', 'Hendersonville', 'Rock Hill', 'Pasadena', 'Clovis',
       'West Lafayette', 'Bismarck', 'Rochester', 'South San Francisco',
       'Bayonne', 'Fargo', 'Powder Springs', 'Germantown', 'Upland',
       'Toa Alta', 'Nashville', 'Normal', 'Buena Park', 'Murfreesboro',
       'Roseville', 'Trujillo Alto', 'Brockton', 'Cary', 'Cordova',
       'Williamsport', 'Azusa', 'Hempstead', 'Provo', 'Canovanas',
       'Zanesville', 'Bartlett', 'Federal Way', 'Lithonia', 'Oviedo',
       'Arlington Heights', 'Manati', 'Ridgewood', 'Vallejo', 'Hickory',
       'Morganton', 'South Gate', 'East Brunswick', 'Medford',
       'Chambersburg', 'Sumner', 'Laguna Hills', 'Lompoc', 'Cayey',
       'Ponce', 'Canoga Park', 'Spokane', 'Freehold', 'Bellingham',
       'Gwynn Oak', 'Lodi', 'CA'], dtype=object)

In [18]:
# total no ofproduct_id
prod_df.columns.tolist()

['Product Card Id',
 'Product Name',
 'Category Id',
 'Category Name',
 'Department Id',
 'Department Name',
 'Product Price']

In [19]:
prod_df['Product Card Id'].nunique()

118

In [23]:
prod_df['Department Id'].nunique()
prod_df['Department Name'].unique()

array(['Fitness', 'Apparel', 'Golf', 'Footwear', 'Outdoors', 'Fan Shop',
       'Technology', 'Book Shop', 'Discs Shop', 'Pet Shop',
       'Health and Beauty '], dtype=object)

In [24]:
prod_df['Product Price'].sum()

np.float64(19636.730023761)

In [25]:
ord_df['Order Id'].nunique()

65752

In [26]:
cust_df["Customer Country"].value_counts()

Customer Country
EE. UU.        12719
Puerto Rico     7933
Name: count, dtype: int64

In [27]:
prod_df.columns.tolist()

['Product Card Id',
 'Product Name',
 'Category Id',
 'Category Name',
 'Department Id',
 'Department Name',
 'Product Price']

In [28]:
prod_df.columns.tolist()

['Product Card Id',
 'Product Name',
 'Category Id',
 'Category Name',
 'Department Id',
 'Department Name',
 'Product Price']

In [29]:
ord_df.columns.tolist()

['Order Id',
 'order date (DateOrders)',
 'Order Status',
 'Order City',
 'Order State',
 'Order Country',
 'Order Region',
 'Market']

In [30]:
ship_df.columns.tolist()

['Order Id',
 'Shipping Mode',
 'Delivery Status',
 'Late_delivery_risk',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'shipping date (DateOrders)']

In [31]:
sales_df.columns.tolist()

['Order Id',
 'Customer Id',
 'Product Card Id',
 'Sales',
 'Order Item Quantity',
 'Benefit per order',
 'Order Profit Per Order']

In [35]:
sales_df[
    (sales_df['Sales'] > 500)
].sort_values(by='Sales', ascending=True)

,Order Id,Customer Id,Product Card Id,Sales,Order Item Quantity,Benefit per order,Order Profit Per Order
175666,71946,15499,1355,532.580017,1,-115.040001,-115.040001
6010,72029,15582,1355,532.580017,1,227.039993,227.039993
6009,71800,15353,1355,532.580017,1,191.250000,191.250000
2351,71937,15490,1355,532.580017,1,123.029999,123.029999
4314,71843,15396,1355,532.580017,1,-306.369995,-306.369995
...,...,...,...,...,...,...,...
141111,68736,8462,208,1999.989990,1,187.580002,187.580002
148399,68806,10351,208,1999.989990,1,34.799999,34.799999
159175,68766,382,208,1999.989990,1,-952.559998,-952.559998
175108,68883,5533,208,1999.989990,1,911.799988,911.799988
12606,68703,9515,208,1999.989990,1,45.000000,45.000000

In [36]:
sales_df[
    (sales_df['Benefit per order'] < 0)
].sort_values(by='Sales', ascending=True)

,Order Id,Customer Id,Product Card Id,Sales,Order Item Quantity,Benefit per order,Order Profit Per Order
32782,10554,2781,775,9.99000,1,-2.020000,-2.020000
32807,7387,3716,775,9.99000,1,-3.660000,-3.660000
32647,41098,2242,775,9.99000,1,-4.000000,-4.000000
32577,54682,5725,775,9.99000,1,-0.410000,-0.410000
32606,48544,9278,775,9.99000,1,-13.190000,-13.190000
...,...,...,...,...,...,...,...
38468,70676,14229,1351,1500.00000,1,-2178.000000,-2178.000000
86153,74528,18081,1351,1500.00000,1,-1176.000000,-1176.000000
148400,68778,986,208,1999.98999,1,-1246.089966,-1246.089966
63989,68859,1428,208,1999.98999,1,-4274.979980,-4274.979980
159175,68766,382,208,1999.98999,1,-952.559998,-952.559998

In [38]:
sales_products = sales_df.merge(
    prod_df,
    on='Product Card Id',
    how='left'
)
sales_products

,Order Id,Customer Id,Product Card Id,Sales,Order Item Quantity,Benefit per order,Order Profit Per Order,Product Name,Category Id,Category Name,Department Id,Department Name,Product Price
0,77202,20755,1360,327.750000,1,91.250000,91.250000,Smart watch,73,Sporting Goods,2,Fitness,327.750000
1,75939,19492,1360,327.750000,1,-249.089996,-249.089996,Smart watch,73,Sporting Goods,2,Fitness,327.750000
2,75938,19491,1360,327.750000,1,-247.779999,-247.779999,Smart watch,73,Sporting Goods,2,Fitness,327.750000
3,75937,19490,1360,327.750000,1,22.860001,22.860001,Smart watch,73,Sporting Goods,2,Fitness,327.750000
4,75936,19489,1360,327.750000,1,134.210007,134.210007,Smart watch,73,Sporting Goods,2,Fitness,327.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
180506,26043,1005,1004,399.980011,1,40.000000,40.000000,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180507,26037,9141,1004,399.980011,1,-613.770019,-613.770019,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180508,26024,291,1004,399.980011,1,141.110001,141.110001,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180509,26022,2813,1004,399.980011,1,186.229996,186.229996,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011
180510,26018,7547,1004,399.980011,1,168.949997,168.949997,Field & Stream Sportsman 16 Gun Fire Safe,45,Fishing,7,Fan Shop,399.980011

In [4]:
cust_df.to_csv("customers.csv", sep=",", index=False)

In [5]:
cust_df

,Customer Id,Customer Fname,Customer Lname,Customer City,Customer State,Customer Country,Customer Segment,Customer Zipcode
0,1,Richard,Hernandez,Brownsville,TX,EE. UU.,Consumer,78521.0
1,2,Mary,Barrett,Littleton,CO,EE. UU.,Consumer,80126.0
2,3,Ann,Smith,Caguas,PR,Puerto Rico,Consumer,725.0
3,4,Mary,Jones,San Marcos,CA,EE. UU.,Consumer,92069.0
4,5,Robert,Hudson,Caguas,PR,Puerto Rico,Home Office,725.0
...,...,...,...,...,...,...,...,...
20647,20753,Chava,Velez,Caguas,PR,Puerto Rico,Consumer,725.0
20648,20754,Stacey,Weber,Plainfield,IL,EE. UU.,Consumer,60544.0
20649,20755,Cally,Holloway,Caguas,PR,Puerto Rico,Consumer,725.0
20650,20756,Cherokee,Callahan,Berwyn,IL,EE. UU.,Corporate,60402.0
20651,20757,Katelyn,Gonzales,Miami,FL,EE. UU.,Corporate,33126.0

In [6]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20652 entries, 0 to 20651
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer Id       20652 non-null  int64
 1   Customer Fname    20652 non-null  object
 2   Customer Lname    20644 non-null  object
 3   Customer City     20652 non-null  object
 4   Customer State    20652 non-null  object
 5   Customer Country  20652 non-null  object
 6   Customer Segment  20652 non-null  object
 7   Customer Zipcode  20649 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.3+ MB

In [7]:
cust_df["Customer Zipcode"].head(20)

0     78521.0
1     80126.0
2       725.0
3     92069.0
4       725.0
5      7055.0
6       725.0
7      1841.0
8       725.0
9     22554.0
10      725.0
11    78227.0
12      725.0
13    90660.0
14    92336.0
15      725.0
16    48180.0
17    94553.0
18      725.0
19     7093.0
Name: Customer Zipcode, dtype: float64

In [8]:
cust_df["Customer Zipcode"].isnull().sum()

np.int64(3)

In [9]:
cust_df.head(100).to_csv("customers_test.csv", index=False)

In [10]:
cust_df["Customer Zipcode"] = (
    cust_df["Customer Zipcode"]
    .fillna(0)
    .astype(int)
)

In [11]:
cust_df.to_csv("customers_clean.csv", index=False)

In [12]:
cust_df["Customer Lname"].isnull().sum()

np.int64(8)

In [13]:
cust_df["Customer Lname"].isnull().sum()

np.int64(8)

In [14]:
cust_df["Customer Lname"] = cust_df["Customer Lname"].fillna("Unknown")

In [15]:
cust_df["Customer Lname"].isnull().sum()

np.int64(0)

In [16]:
cust_df.isnull().sum()

Customer Id         0
Customer Fname      0
Customer Lname      0
Customer City       0
Customer State      0
Customer Country    0
Customer Segment    0
Customer Zipcode    0
dtype: int64

In [17]:
cust_df = cust_df.fillna("Unknown")
cust_df.to_csv("customers_clean.csv", index=False)

In [18]:
prod_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product Card Id  118 non-null    int64
 1   Product Name     118 non-null    object
 2   Category Id      118 non-null    int64
 3   Category Name    118 non-null    object
 4   Department Id    118 non-null    int64
 5   Department Name  118 non-null    object
 6   Product Price    118 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 6.6+ KB

In [19]:
prod_df.isnull().sum()

Product Card Id    0
Product Name       0
Category Id        0
Category Name      0
Department Id      0
Department Name    0
Product Price      0
dtype: int64

In [21]:
prod_df.to_csv("products_clean.csv", sep=",", index=False)

In [22]:
prod_df.head()
prod_df.to_csv("products_test.csv", index=False, encoding="utf-8")

In [23]:
prod_df["Product Price"].describe()

count     118.000000
mean      166.412966
std       262.184328
min         9.990000
25%        31.990000
50%        87.195000
75%       199.990005
max      1999.989990
Name: Product Price, dtype: float64

In [24]:
prod_df["Category Id"].max()

np.int64(76)

In [25]:
prod_df["Department Id"].max()

np.int64(12)

In [26]:
print(prod_df["Category Id"].max())
print(prod_df["Department Id"].max())
print(prod_df["Product Card Id"].max())

76
12
1363

In [27]:
print(prod_df["Product Name"].str.len().max())
print(prod_df["Category Name"].str.len().max())
print(prod_df["Department Name"].str.len().max())

45
20
18

In [28]:
prod_df["Product Card Id"] = prod_df["Product Card Id"].astype(int)
prod_df["Category Id"] = prod_df["Category Id"].astype(int)
prod_df["Department Id"] = prod_df["Department Id"].astype(int)

prod_df["Product Price"] = pd.to_numeric(
    prod_df["Product Price"],
    errors="coerce"
)

prod_df.to_csv(
    r"D:\SQL\Supply_Chain_Mgmt\Python_Codes\products_sql.csv",
    index=False
)

In [31]:
prod_df.to_csv(
    r"D:\SQL\Supply_Chain_Mgmt\Python_Codes\products_sql.csv",
    index=False,
    encoding="utf-8"
)

In [32]:
prod_df = prod_df.drop_duplicates()

In [33]:
print(prod_df.shape)

(118, 7)

In [34]:
text_cols = [
    "Product Name",
    "Category Name",
    "Department Name"
]

for col in text_cols:
    prod_df[col] = prod_df[col].str.strip()

In [35]:
prod_df["Product Card Id"] = prod_df["Product Card Id"].astype(int)
prod_df["Category Id"] = prod_df["Category Id"].astype(int)
prod_df["Department Id"] = prod_df["Department Id"].astype(int)

prod_df["Product Price"] = pd.to_numeric(
    prod_df["Product Price"],
    errors="coerce"
)

In [37]:
prod_df.to_csv(
    r"D:\SQL\Supply_Chain_Mgmt\Data\products_clean.csv",
    index=False
)

In [38]:
prod_df.dtypes

Product Card Id      int64
Product Name        object
Category Id          int64
Category Name       object
Department Id        int64
Department Name     object
Product Price      float64
dtype: object

In [39]:
prod_df.head()

,Product Card Id,Product Name,Category Id,Category Name,Department Id,Department Name,Product Price
0,1360,Smart watch,73,Sporting Goods,2,Fitness,327.750000
1,365,Perfect Fitness Perfect Rip Deck,17,Cleats,4,Apparel,59.990002
2,627,Under Armour Girls' Toddler Spine Surge Runni,29,Shop By Sport,5,Golf,39.990002
3,502,Nike Men's Dri-FIT Victory Golf Polo,24,Women's Apparel,5,Golf,50.000000
4,278,Under Armour Men's Compression EV SL Slide,13,Electronics,3,Footwear,44.990002

In [40]:
prod_df.describe(include='all')

,Product Card Id,Product Name,Category Id,Category Name,Department Id,Department Name,Product Price
count,118.000000,118,118.000000,118,118.000000,118,118.000000
unique,NaN,118,NaN,50,NaN,11,NaN
top,NaN,Smart watch,NaN,Electronics,NaN,Outdoors,NaN
freq,NaN,1,NaN,11,NaN,53,NaN
mean,689.576271,NaN,33.449153,NaN,5.296610,NaN,166.412966
std,403.120380,NaN,19.292883,NaN,2.097248,NaN,262.184328
min,19.000000,NaN,2.000000,NaN,2.000000,NaN,9.990000
25%,303.500000,NaN,17.000000,NaN,3.250000,NaN,31.990000
50%,729.000000,NaN,35.000000,NaN,6.000000,NaN,87.195000
75%,905.750000,NaN,40.750000,NaN,6.000000,NaN,199.990005
max,1363.000000,NaN,76.000000,NaN,12.000000,NaN,1999.989990

In [41]:
prod_df.apply(lambda x: x.astype(str).str.len().max())

Product Card Id     4
Product Name       45
Category Id         2
Category Name      20
Department Id       2
Department Name    17
Product Price      11
dtype: int64